### ISSUE TITLE
Fib Algorithms Build

### ISSUE THREAD

**Issue by mapra99** [migueling2015/fibonacci-vis#3]
Build all variants of Fibonacci Algorithms.
More info to come from @migueling2015

**Comment by migueling2015** [comment]
Ey men @mapra99 I have create the logic for one of the workers

**Comment by mapra99** [comment]
super! ya tengo el visor para el worker

**Comment by mapra99** [comment]
Mira el #10

**Comment by migueling2015** [comment]
Ya dejé en Development la lógica del primer Fibo, revisa los cambios al html por fa

**Comment by migueling2015** [comment]
Hola, listo, también el dinámico

**Comment by mapra99** [comment]
👍
